package com.zdroid

import android.content.Context
import android.content.Intent
import android.hardware.input.InputManager
import android.os.Build
import android.view.InputDevice
import androidx.core.content.FileProvider
import java.io.File
import java.text.SimpleDateFormat
import java.util.ArrayDeque
import java.util.Date
import java.util.Locale

/// On-device diagnostic exporter.
///
/// User apps can't read another app's logcat without READ_LOGS — that's a
/// signature-level permission and there's no user-facing grant path. A
/// reporter with no PC + ADB therefore can't dump Zdroid's logs via Termux
/// or any other shell on the device. Instead we maintain a small ring of
/// the log lines worth shipping inside Zdroid itself, and offer a one-tap
/// "Export Diagnostic" that drops the dump into Android's share sheet so
/// the user can email / Drive / upload it to a GitHub issue.
///
/// File destination is `cacheDir/diagnostic/zdroid-diag-<stamp>.txt`; the
/// path is whitelisted by `updater_file_paths.xml` so the existing
/// `com.zdroid.updater.fileprovider` authority can mint the content:// URI
/// for ACTION_SEND.
object Diagnostic {
    private const val RING_CAPACITY = 500

    private val ring = ArrayDeque<String>()

    @JvmStatic
    fun record(tag: String, level: Char, message: String) {
        val line = "${timestamp()} $level/$tag: $message"
        synchronized(ring) {
            if (ring.size >= RING_CAPACITY) ring.pollFirst()
            ring.addLast(line)
        }
    }

    @JvmStatic
    fun composeDump(context: Context, extras: String?): File {
        val sb = StringBuilder()
        sb.appendLine("# Zdroid diagnostic ${isoTimestamp()}")
        sb.appendLine()
        appendDeviceSection(sb)
        appendAppSection(sb, context)
        appendInputDevicesSection(sb, context)
        if (!extras.isNullOrEmpty()) {
            sb.appendLine("## Runtime state (gpui_android)")
            sb.appendLine(extras.trim())
            sb.appendLine()
        }
        appendRingSection(sb)

        val dir = File(context.cacheDir, "diagnostic").apply { mkdirs() }
        val stamp = SimpleDateFormat("yyyyMMdd-HHmmss", Locale.US).format(Date())
        val file = File(dir, "zdroid-diag-$stamp.txt")
        file.writeText(sb.toString())
        return file
    }

    @JvmStatic
    fun share(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(
            context,
            "com.zdroid.updater.fileprovider",
            file,
        )
        val send = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "Zdroid diagnostic ${file.name}")
            putExtra(
                Intent.EXTRA_TEXT,
                "Diagnostic attached. Generated by Export Diagnostic in Zdroid.",
            )
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        val chooser = Intent.createChooser(send, "Share Zdroid diagnostic")
        // FLAG_ACTIVITY_NEW_TASK is needed if the caller hands a non-
        // Activity context; harmless when the caller IS an Activity.
        chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(chooser)
    }

    private fun appendDeviceSection(sb: StringBuilder) {
        sb.appendLine("## Device")
        sb.appendLine("manufacturer: ${Build.MANUFACTURER}")
        sb.appendLine("model:        ${Build.MODEL}")
        sb.appendLine("device:       ${Build.DEVICE}")
        sb.appendLine("product:      ${Build.PRODUCT}")
        sb.appendLine("brand:        ${Build.BRAND}")
        sb.appendLine("release:      Android ${Build.VERSION.RELEASE}")
        sb.appendLine("sdk:          ${Build.VERSION.SDK_INT}")
        sb.appendLine("fingerprint:  ${Build.FINGERPRINT}")
        sb.appendLine()
    }

    private fun appendAppSection(sb: StringBuilder, context: Context) {
        sb.appendLine("## App")
        sb.appendLine("package:      ${context.packageName}")
        val pkg = try {
            context.packageManager.getPackageInfo(context.packageName, 0)
        } catch (t: Throwable) {
            sb.appendLine("packageInfo failed: ${t.message}")
            null
        }
        if (pkg != null) {
            sb.appendLine("versionName:  ${pkg.versionName}")
            sb.appendLine("versionCode:  ${pkg.longVersionCode}")
        }
        sb.appendLine()
    }

    private fun appendInputDevicesSection(sb: StringBuilder, context: Context) {
        sb.appendLine("## Input devices")
        try {
            val im = context.getSystemService(InputManager::class.java)
            if (im == null) {
                sb.appendLine("(InputManager unavailable)")
            } else {
                for (id in im.inputDeviceIds) {
                    val d = im.getInputDevice(id) ?: continue
                    sb.appendLine("- id=$id name=\"${d.name}\"")
                    sb.appendLine("    vendorId=0x${d.vendorId.toString(16)} productId=0x${d.productId.toString(16)}")
                    sb.appendLine("    sources=0x${d.sources.toString(16)} (${sourcesToNames(d.sources)})")
                    sb.appendLine("    keyboardType=${keyboardTypeName(d.keyboardType)} isVirtual=${d.isVirtual} isExternal=${d.isExternal}")
                }
            }
        } catch (t: Throwable) {
            sb.appendLine("(enumeration failed: ${t.message})")
        }
        sb.appendLine()
    }

    private fun appendRingSection(sb: StringBuilder) {
        val snapshot: List<String>
        synchronized(ring) { snapshot = ring.toList() }
        sb.appendLine("## Ring buffer (${snapshot.size} lines)")
        for (line in snapshot) sb.appendLine(line)
    }

    private fun timestamp(): String =
        SimpleDateFormat("HH:mm:ss.SSS", Locale.US).format(Date())

    private fun isoTimestamp(): String =
        SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS", Locale.US).format(Date())

    private fun sourcesToNames(sources: Int): String {
        val names = mutableListOf<String>()
        // Each Android InputDevice.SOURCE_* constant is a bitfield; AND
        // each against the device's sources mask and label the ones that
        // light up. Order matters only for readability.
        fun check(mask: Int, name: String) {
            if (sources and mask == mask) names.add(name)
        }
        check(InputDevice.SOURCE_KEYBOARD, "KEYBOARD")
        check(InputDevice.SOURCE_DPAD, "DPAD")
        check(InputDevice.SOURCE_GAMEPAD, "GAMEPAD")
        check(InputDevice.SOURCE_TOUCHSCREEN, "TOUCHSCREEN")
        check(InputDevice.SOURCE_MOUSE, "MOUSE")
        check(InputDevice.SOURCE_MOUSE_RELATIVE, "MOUSE_RELATIVE")
        check(InputDevice.SOURCE_STYLUS, "STYLUS")
        check(InputDevice.SOURCE_TRACKBALL, "TRACKBALL")
        check(InputDevice.SOURCE_TOUCHPAD, "TOUCHPAD")
        check(InputDevice.SOURCE_JOYSTICK, "JOYSTICK")
        return if (names.isEmpty()) "NONE" else names.joinToString("|")
    }

    private fun keyboardTypeName(kt: Int): String = when (kt) {
        InputDevice.KEYBOARD_TYPE_NONE -> "NONE"
        InputDevice.KEYBOARD_TYPE_NON_ALPHABETIC -> "NON_ALPHABETIC"
        InputDevice.KEYBOARD_TYPE_ALPHABETIC -> "ALPHABETIC"
        else -> "type=$kt"
    }
}
